### ISSUE TITLE
同板子支持一下

### ISSUE THREAD

**Issue by a63680421** [goomadao/MSI-H410M-A-PRO-OpenCore-EFI#1]
除了没网卡其他基本跟你一样我担心显卡风扇挡住pcie是否能插进去，这个usb问题终于有解决了添加后比原版识别出更多的端口，我用Hackintool定制usb的过程中发现主板4个usb2.0只有两个插入有显示，但是使用没问题，igfxfw=2这个参数我是加到启动里的，加入这个参数会无法睡眠我看到你是注入显卡里的我也试了可以睡眠注入显卡中是否有效告知下。 DRM的问题启动加入shikigva=80即可，我定制了cpu变频 usb可以加入USBPower开启额外充电 570可以使用radeonboost.kext或者ssdt我目前使用了后者
https://www.tonymacx86.com/threads/amd-radeon-performance-enhanced-ssdt.296555/page-87
这块主板之前有个问题我有遇到igpu显存设置64m会掉到32m Above 4G decoding有时候会关闭，bios更新后暂时没遇到了。

**Comment by goomadao** [comment]
1.网卡我是用的m.2口
2.这个主板后面的四个USB2.0都在一个USB Hub上，因此四个USB2.0都在同一个位置
3.我是可以正常睡眠的
4.DRM我尝试过加入shikigva=80，在10.15.6下无法播放[Amazon Prime](https://www.amazon.com/Spider-Man-Far-Home-Tom-Holland/dp/B07TP6D1DP)的Trailer。刚刚我在Big Sur public beta 1试了一下，居然可以。可以告知一下你的系统版本吗？
5.CPU我看能正常低频和睿频转换，就没有自己定制了，请问定制了过后有什么改进吗？

**Comment by a63680421** [comment]
网卡我是想买插主板上天线的话是接那种带孔的挡板是吗不装的话好像是信号很弱。usb这个发现了都在usb hub一个位置上，我是10.15.6试了下你的链接可以播放添加启动参数可能需要nvram清空，变频的解释你可以看下这个博客4.1章节的说明https://blog.xjn819.com/，这块主板虽然丐其实还是有可以设置的地方的内存我降序到c15 c14也可以需要加电压c15 1.2v就可以稳定，cpu l1 l2微星给了130w 180w可以锁定这个功耗虽然比默认高了20w但是单核会有一些提升高频率能维持更长的时间微星工程师说这么说的cpu进阶设置里spread spectrum设置为关闭总线速度会稳定100。

**Comment by goomadao** [comment]
🉑️
