### ISSUE TITLE
Microphone not working

### ISSUE THREAD

**Issue by Simone-cm** [goomadao/MSI-H410M-A-PRO-OpenCore-EFI#11]
Hello.

In latest release, microphone is not working but audio is fine. Any idea on what it could be?

Using:
- MSI H410M Pro
- i3 10100F
- RX 5600 XT
- Latest EFI (0.6.7)

**Comment by Simone-cm** [comment]
I solved the issue!

Change the layout-id from 4 to 3 and bam you have audio ;)

**Comment by goomadao** [comment]
Thanks. I will update the layout-id to 3 later.
BTW, are you using AirPods with this EFI in Big Sur? There are problems with my AirPods Pro while using Big Sur, but it works well when it comes to Catalina, which is really confusing and I have no idea how to fix it.

**Comment by Simone-cm** [comment]
How are you using the bluetooth? Bluetooth USB or...?

**Comment by goomadao** [comment]
Apple's WiFi card BCM94360CS2. It should be supported officially in macOS.

**Comment by Simone-cm** [comment]
It is very strange! Unfortunately I have no idea but I was contemplating on buying a Bluetooth card to use AirPods Pro as well.

I have a Xiaomi Notebook Pro using itlwm and they work fine, almost like if it was a real MacBook.

Maybe you can try using a third party kext for the WiFi card? Or maybe you need en0 on that card? No idea :(

**Comment by goomadao** [comment]
Well I've tried `AirportBrcmFixup` and `BrcmPatchRAM`, but they didn't work. I'm about to replace the motherboard, hope it can work.
