### ISSUE TITLE
关于显卡提问

### ISSUE THREAD

**Issue by ghost** [goomadao/MSI-H410M-A-PRO-OpenCore-EFI#12]
麻烦问一下，您是把你的显卡出掉了嘛哈哈哈？

我现在也想把我的显卡出掉，然后买一个和你一样的CPU。想问一下，单独使用独显的话，性能会有降低吗？我日常也就是影音浏览，偶尔剪剪片子。

**Comment by goomadao** [comment]
打算出掉，不过还有点犹豫。因为这个板子没有DP，用HDMI的话休眠过后无法正常唤醒，需要关显示器再打开才能唤醒，并且这个板子的HDMI 4K只支持到30HZ。再加上AirPods的问题，我打算过段时间先换个带DP的B560主板，如果唤醒和AirPods正常我再出掉显卡。


> 单独使用独显的话，性能会有降低吗？我日常也就是影音浏览，偶尔剪剪片子。

你想问的应该是单独使用核显吧？硬解码都正常，不过我不剪片子，对这方面不太了解。

**Comment by ghost** [comment]
嗯，如果不能用airpods那确实是一个很大的问题了。
我盈通rx580去年358买的，早晨去淘宝店铺看了一下，店铺挂的1500😂，我准备咸鱼挂1200，看能不能卖掉。真的是个好价钱啊。
cpu目前我是10100f，准备换成和你一样的，看了很多评论，都说es的u挺稳定的，就是性能稍微差点。
休眠功能我用的比较少诶，没有遇到过你说的问题。我现在EFI版本是你上一个版本，用核显，很完美了。


如果出得话建议现在出，h410最近普遍涨了50块钱，目前出手似乎是个不错的选择。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "goomadao/MSI-H410M-A-PRO-OpenCore-EFI"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 中午11:19
收件人:&nbsp;"goomadao/MSI-H410M-A-PRO-OpenCore-EFI"<MSI-H410M-A-PRO-OpenCore-EFI@noreply.github.com&gt;;
抄送:&nbsp;"赵志成"<505788057@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [goomadao/MSI-H410M-A-PRO-OpenCore-EFI] 关于显卡提问 (#12)



 打算出掉，不过还有点犹豫。因为这个板子没有DP，用HDMI的话休眠过后无法正常唤醒，需要关显示器再打开才能唤醒，并且这个板子的HDMI 4K只支持到30HZ。再加上AirPods的问题，我打算过段时间先换个带DP的B560主板，如果唤醒和AirPods正常我再出掉显卡。
  单独使用独显的话，性能会有降低吗？我日常也就是影音浏览，偶尔剪剪片子。
  你想问的应该是单独使用核显吧？硬解码都正常，不过我不剪片子，对这方面不太了解。

**Comment by goomadao** [comment]
现在b560没有什么好的选择。本来想换华擎的itx，可是又觉得太丐了。再等一段时间吧。显卡的话闲鱼问了一圈最高有出到1050回收的
