### ISSUE TITLE
15.7系统 VDA解码器 解码失败 VideoProc 看不到显卡

### ISSUE THREAD

**Issue by token8848** [goomadao/MSI-H410M-A-PRO-OpenCore-EFI#5]
1、15.7系统 VDA解码器 解码失败 VideoProc 看不到显卡

<img width="275" alt="Snipaste_2020-12-08_21-43-38" src="https://user-images.githubusercontent.com/72897509/101491287-8857bf00-399e-11eb-9a61-0d04813e3f89.png">
<img width="888" alt="Snipaste_2020-12-08_21-43-58" src="https://user-images.githubusercontent.com/72897509/101491304-8b52af80-399e-11eb-8561-ad8ee5831881.png">

2、但是sensei看是能看到显卡的
<img width="1021" alt="Snipaste_2020-12-08_21-44-57" src="https://user-images.githubusercontent.com/72897509/101491432-b0dfb900-399e-11eb-88dd-a1711fe7cb89.png">

3、OC0.6.4 release了，有没有考虑升级一下？

**Comment by goomadao** [comment]
1我记得之前我是可以看到的，现在不知道能不能看到，我现在只用Bug Sur。3的话最近可能没时间，可能会晚一点更新，也可能会下个月等0.6.5发布再升级

**Comment by token8848** [comment]
关于本机-系统报告 的 图形卡/显示器 里只能看到独显Rx580,如果核显也正常驱动，这里是不是应该还有个UHD630？

**Comment by token8848** [comment]
另外，deviceproperties里PciRoot(0x0)/Pci(0x2,0x0)下，igfxfw 02000000 这个字段是做什么用的？

**Comment by token8848** [comment]
PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0) 里 shikigva 80 又是做什么用的呢？

**Comment by token8848** [comment]
我找到原因了，BIOS里要把集显多显示器输出开启，不然bios自己屏蔽核显。
开启后
系统报告中仍然只有独显
但是VDA解码器 已经完全支持，videoproc里也能显示硬解了

另外，deviceproperties里PciRoot(0x0)/Pci(0x2,0x0)下，igfxfw 02000000 这个字段是做什么用的？
PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0) 里 shikigva 80 又是做什么用的呢？

**Comment by goomadao** [comment]
igfxfw应该是WhateverGreen的一个参数，具体什么用我想不起来了
shikigva是用来修复DRM的，https://dortania.github.io/OpenCore-Post-Install/universal/drm.html#fixing-drm 这里面有介绍

**Comment by token8848** [comment]
> igfxfw 应该是 WhateverGreen 的一个参数，具体什么用我想不起来了
> shikigva 是用来修复 DRM 的，https://dortania.github.io/OpenCore-Post-Install/universal/drm.html#fixing-drm 这里面有介绍

WhateverGreen 里找到这一行，那为什么要添加在PciRoot (0x0)/Pci (0x2,0x0)下呢？
igfxfw=2 boot argument (and igfxfw property) to force loading of Apple GuC firmware

**Comment by goomadao** [comment]
想不起来了。应该还是在Dortania里面写的。就一直保留下来了
