### ISSUE TITLE
几点反馈

### ISSUE THREAD

**Issue by falaQAQX** [goomadao/MSI-H410M-A-PRO-OpenCore-EFI#8]
碰巧和楼主同款主板，也吃苹果，根据dortania guide的同时也参考了楼主的efi
1. 前后面板的 **音频输入** 好像不能用？音频输出是可以用的，目测要换layout？
2. 使用iMac 20,1 用了以后可以识别出前面板USB，我也是遇到问题后看到了楼主的readme，我抱着试一试的心态把楼主USBInjectAll中plist给加上了IMac20,1的信息(就是dictionary item复制一下再把机型改成iMac20,1，因为我看iMac这几个item除了机型名称其它全部一样。重启后识别出来了HS01-10 SS01-05).   其中HS05上是后面板4个2.0接口的hub，楼主可以参考我的usbmap，我把所有的USB接口都测了一遍(包括机箱前面板的两个2.0和两个3.0)。改好的文件如下。我没用Broadcom的无线网卡，所以蓝牙的问题就不知道了。
[USBMap.kext.zip](https://github.com/goomadao/MSI-H410M-A-PRO-OpenCore-EFI/files/5682613/USBMap.kext.zip)
[USBInjectAll.kext.zip](https://github.com/goomadao/MSI-H410M-A-PRO-OpenCore-EFI/files/5682615/USBInjectAll.kext.zip)
3. 楼主确定Big Sur的DRM能用？dortania guide里直接说了还不能。
4. 这款主板BIOS里可以直接解锁CFG Lock，楼主不解锁一下？
5. 还有很多BIOS设置需要在默认上修改，当然楼主不打算做保姆教程的话不添加也无所谓了。
ps: 我BIOS版本更了当前最新的，用的是Catalina，opencore 0.6.4。

**Comment by goomadao** [comment]
1. 音频输入这个我确实没试过，之前做EFI的时候只保证了输出可以用，现在我都用AirPods基本不用有线耳机了，如果找到了合适的layout可以告知一下我在repo中修改
2. 有空的时候我试一下，感谢
3. 我这里测试，Big Sur看Amazon那个Far From Home的Trailer没问题，Apple TV的没有试
4. 已经解锁了
5. 确实需要改一些BIOS，这些按照Dortania Guide来基本就行了，不过本来也不是打算做教程，只是给有需要的人参考一下

**Comment by iihll** [comment]
> 碰巧和楼主同款主板，也吃苹果，根据dortania guide的同时也参考了楼主的efi
> 
> 1. 前后面板的 **音频输入** 好像不能用？音频输出是可以用的，目测要换layout？
> 2. 使用iMac 20,1 用了以后可以识别出前面板USB，我也是遇到问题后看到了楼主的readme，我抱着试一试的心态把楼主USBInjectAll中plist给加上了IMac20,1的信息(就是dictionary item复制一下再把机型改成iMac20,1，因为我看iMac这几个item除了机型名称其它全部一样。重启后识别出来了HS01-10 SS01-05).   其中HS05上是后面板4个2.0接口的hub，楼主可以参考我的usbmap，我把所有的USB接口都测了一遍(包括机箱前面板的两个2.0和两个3.0)。改好的文件如下。我没用Broadcom的无线网卡，所以蓝牙的问题就不知道了。
>    [USBMap.kext.zip](https://github.com/goomadao/MSI-H410M-A-PRO-OpenCore-EFI/files/5682613/USBMap.kext.zip)
>    [USBInjectAll.kext.zip](https://github.com/goomadao/MSI-H410M-A-PRO-OpenCore-EFI/files/5682615/USBInjectAll.kext.zip)
> 3. 楼主确定Big Sur的DRM能用？dortania guide里直接说了还不能。
> 4. 这款主板BIOS里可以直接解锁CFG Lock，楼主不解锁一下？
> 5. 还有很多BIOS设置需要在默认上修改，当然楼主不打算做保姆教程的话不添加也无所谓了。
>    ps: 我BIOS版本更了当前最新的，用的是Catalina，opencore 0.6.4。

layout id 可以试试 1 我的输入输出均没有问题
