### ISSUE TITLE
相同板子 usb 问题

### ISSUE THREAD

**Issue by iihll** [goomadao/MSI-H410M-A-PRO-OpenCore-EFI#9]
楼主制作efi时有没遇到 不使用SSDT-RHUB.aml 只有前面板usb2.0可识别的情况 我使用了repo里的usbmap后所有接口都可使用，但是hackintool中显示不出插入的usb 只有前面板两个usb2.0插入时会显示绿色识别出

**Comment by goomadao** [comment]
我这里使用RHUB会导致无法引导Windows，所以就没有用RHUB了，在hackintool里面显示正常

**Comment by iihll** [comment]
> 我这里使用RHUB会导致无法引导Windows，所以就没有用RHUB了，在hackintool里面显示正常
